language: rust
sudo: false

cache: cargo
cache:
    directories:
      - $HOME/.cargo
      - $HOME/target

before-cache:
  - rm -rf $HOME/.cargo/registry

rust:
  - beta
  - nightly

matrix:
    allow_failures:
      - rust: nightly
    fast_finish: true
    include:
      - os: linux
        rust: stable
        compiler: gcc

      - os: windows
        rust: stable

      - os: osx
        rust: stable

script:
  - cargo test --all --all-features
